### ISSUE TITLE
KNL cross-compile fails due to ABT_CONFIG_USE_FCONTEXT being unset

### ISSUE THREAD

**Issue by kevin-harms** [pmodels/argobots#11]
I was trying to build master on Theta setting
./configure --prefix=<path> --host x86_64 CFLAGS="-03 -xMIC-AVX512"
the configure complete but the build fails with:

  CC       libabt_la-barrier.lo
In file included from ../src/include/abtd.h(48),
                 from ../src/include/abti.h(126),
                 from barrier.c(6):
../src/include/abtd_thread.h(162): error: #error directive: "Not implemented yet"
  #error "Not implemented yet"

Removing the KNL specific option and --host parameter will allow the build to complete.

**Comment by shintaro-iwasaki** [comment]
it is needed to specify the host OS as well. For example, in your case,
```
./configure --prefix=[...] --host x86_64-pc-linux-gnu --enable-fast=O3 CFLAGS="-xMIC-AVX512"
```
works with the latest Argobots and Intel C Compiler.

This issue is due to failure of obtaining `host_os` in `configure`. It is necessary to determine the assembly version of `fcontext`. `ucontext` should be a fallback, but "not implemented yet" at this moment (see also #18)
