### ISSUE TITLE
Argobots mutex unlock prematurely?

### ISSUE THREAD

**Issue by danghvu** [pmodels/argobots#14]
Here is a test case that I think having a race-condition and fail occasionally when I try to cleanup a mutex. I compiled (with gcc 4.9.1) and ran with master branch latest commit.

```bash
while ./hello_world_thread; do :; done
...
[U1:E1] Hello, world!
[U0:E0] Hello, world!
lt-hello_world_thread: thread_htable.c:48: ABTI_thread_htable_free: Assertion `!ret' failed.
Aborted (core dumped)
```

It works with pthread mutex and condition variable (`USE_PTH_MUTEX`). I believe this is due to Argobot still held some internal lock during unlock.

```c
#include <stdio.h>
#include "abt.h"

#define NUM_XSTREAMS    2
// Comment this out to use ABT
// #define USE_PTH_MUTEX

#ifndef USE_PTH_MUTEX
ABT_cond c;
ABT_mutex m;
#else
#include <pthread.h>
pthread_cond_t c;
pthread_mutex_t m;
#endif

volatile int run = 0;
volatile int flag = 0;

void thread_hello(void *arg)
{
    int rank, tid = (int)(size_t)arg;
    ABT_xstream_self_rank(&rank);
    if (tid == 0) {
      while (!run) {};
#ifndef USE_PTH_MUTEX
      ABT_mutex_lock(m);
      flag = 1;
      ABT_cond_signal(c);
      ABT_mutex_unlock(m);
#else
      pthread_mutex_lock(&m);
      flag = 1;
      pthread_cond_signal(&c);
      pthread_mutex_unlock(&m);
#endif
    } else {
#ifndef USE_PTH_MUTEX
      ABT_mutex_lock(m);
      run = 1;
      while (!flag)
        ABT_cond_wait(c, m);
      ABT_mutex_unlock(m);
      ABT_mutex_free(&m);
#else
      pthread_mutex_lock(&m);
      run = 1;
      while (!flag)
        pthread_cond_wait(&c, &m);
      pthread_mutex_unlock(&m);
      pthread_mutex_destroy(&m);
#endif
    }
    printf("[U%d:E%d] Hello, world!\n", tid, rank);
}

int main(int argc, char *argv[])
{
    ABT_xstream xstreams[NUM_XSTREAMS];
    ABT_pool    pools[NUM_XSTREAMS];
    int i;

    ABT_init(argc, argv);

    /* Create ESs */
    ABT_xstream_self(&xstreams[0]);
    for (i = 1; i < NUM_XSTREAMS; i++) {
        ABT_xstream_create(ABT_SCHED_NULL, &xstreams[i]);
    }

    /* Get the first pool associated with each ES */
    for (i = 0; i < NUM_XSTREAMS; i++) {
        ABT_xstream_get_main_pools(xstreams[i], 1, &pools[i]);
    }

#ifndef USE_PTH_MUTEX
    ABT_cond_create(&c);
    ABT_mutex_create(&m);
#else
    pthread_mutex_init(&m, 0);
    pthread_cond_init(&c, 0);
#endif

    /* Create ULTs */
    for (i = 0; i < NUM_XSTREAMS; i++) {
        ABT_thread_create(pools[i], thread_hello, (void *)(size_t)i,
                          ABT_THREAD_ATTR_NULL, NULL);
    }

    for (i = 1; i < NUM_XSTREAMS; i++) {
        ABT_xstream_join(xstreams[i]);
        ABT_xstream_free(&xstreams[i]);
    }

    ABT_finalize();

    return 0;
}
```

**Comment by shintaro-iwasaki** [comment]
This bug seems to happen because of the improper `thread_htable`'s management.

1. `ABT_mutex_unlock` calls `ABTI_mutex_unlock`.
https://github.com/pmodels/argobots/blob/master/src/mutex.c#L434
2.  `ABTI_mutex_unlock` calls  `ABTI_mutex_wake_de` _after_ releasing the lock of a mutex.
https://github.com/pmodels/argobots/blob/master/src/include/abti_mutex.h#L205
3. `ABTI_mutex_wake_de` uses `thread_htable`'s lock (actually, this lock is a `pthread_lock`)
https://github.com/pmodels/argobots/blob/master/src/mutex.c#L767
4. However, other threads can take a lock of this mutex (because it is released in 2), release it, and free it. When mutex is released, `thread_htable` is also freed.
5. 3 and 4 can happen simultaneously, which is observed as a failure of `ABTI_thread_htable_free` in 4 because that `thread_htable` is still used in 3.

To address this problem, `thread_htable` should be protected by its mutex's lock (see 
https://github.com/pmodels/argobots/blob/master/src/include/abti_mutex.h#L205).
However, just reordering function calls at L203-205 incurs different problems.

**Comment by shintaro-iwasaki** [comment]
We removed the `thread_htable` mechanism since it had many issues (#14, #34, #41), so this issue should have been solved. The new `ABT_mutex` implementation should not have this issue.
