### ISSUE TITLE
Enhancement of the pool interface

### ISSUE THREAD

**Issue by s417-lama** [pmodels/argobots#154]
The current pool interface can realize a very simple queue implementation (e.g., FIFO), but it is not sufficient as a generic API for a queue.

The current API looks like:
```
ABT_pool_push(ABT_pool pool, ABT_unit unit);
ABT_pool_pop(ABT_pool pool, ABT_unit *unit);
```
We cannot tell if push/pop is local or remote and in which context it is called.
For example, a typical work stealing queue cannot be implemented by the current interface.

I propose an extension for the pool interface that passes an operation type as an argument:

```
ABT_pool_push_ex(ABT_pool pool, ABT_unit unit, ABT_pool_op op);
ABT_pool_pop_ex(ABT_pool pool, ABT_unit *unit, ABT_pool_op op);
```

- the runtime passes predefined `op`s in Argobots functions
    - e.g., `ABT_POOL_OP_YIELD` at `ABT_thread_yield`
- users can define their own `op`s that can be passed in schedulers
    - e.g., `op` can be defined by users from range `ABT_POOL_OP_USER_MIN` to `ABT_POOL_OP_USER_MAX`

A work stealing queue can be implemented in the following way:

- If `op` is `ABT_POOL_OP_YIELD` in `ABT_pool_push_ex`, the worker pushes the work unit to the end of the queue
- In the scheduler, pop a work unit from its own queue by passing `ABT_POOL_OP_POP_LOCAL` (user-defined) to `ABT_pool_push_ex()`.
- In the scheduler, steal a work unit from another worker's queue by passing `ABT_POOL_OP_STEAL` (user-defined) to `ABT_pool_push_ex()`.
- When a work unit is created, it passes `ABT_POOL_OP_CREATE` to `ABT_pool_push()` by default
    - It's not sufficient for a work stealing queue; we should distinguish if the push is local or remote.
    - Maybe pass an `op` to `ABT_thread_create_ex()`?

What do you think about this enhancement?

**Comment by shintaro-iwasaki** [comment]
Thank you for making an issue. We need a more flexible interface. Actually I heard requests from many about improving the current limited pool design.

One of the biggest problems is that we cannot implement a typical Cilk-like work-stealing queue with the current pool. Argobots should provide flexibility as much as possible and at least can implement the typical one like this:

- Two types of push:
  - `[Create]` Push a ULT to the head of the local pool
    - A newly created ULT should be scheduled soon for better locality.
  - `[Yield]` Push a ULT to the tail of the local pool so that
    - A yielded ULT should be scheduled later.
- Two types of pop
  - `[Local]` Pops a ULT from the head of the local pool
    - It is for better locality (newly created ULTs are near the head).
  - `[Remote]` Pops a ULT from the *tail* of the remote pool
     - A ULT at the tail tends to have larger work

I will make a prototype soon, but it will be a quite big change.
I welcome any feedback.

**Comment by shintaro-iwasaki** [comment]
Just a note, but the current custom pool has several design flaws.

1. Users cannot mix multiple custom pools since the current design forces a single `ABT_thread/task` <=> `ABT_unit` mapping.
   - It is extremely hard to change an associated pool from one pool to another if they use different `ABT_unit` implementation, although it is not impossible if one uses, for example, a hash table.
2. Some functions should take `pool` as an argument since their functionalities are specific to the pool implementation.
   - For example, `ABT_unit_is_in_pool_fn()` requires `ABT_pool` as an argument if the pool implementation uses a ring buffer.  Maybe `ABT_unit_create_from_thread_fn()` wants to take `ABT_pool` as an argument to cache some data structures.
3. Some functions cannot be implemented efficiently.
   - `ABT_unit_is_in_pool_fn()` is not easy to implement if the underlying implementation uses a ring buffer.
   - `ABT_pool_get_size_fn()` requires counter management, but most lock-free algorithms do not support such (or add an atomic counter just for this function).  I believe in most cases, `is_empty()` is sufficient.
4. `ABT_pool_pop_timedwait_fn()` is marked as deprecated.  It should be removed in the future.
5. `ABT_pool_remove_fn()` cannot be implemented efficiently with most lock-free algorithms.  This does not impose atomicity, so even if it is optional, this function can be hardly used.   In practice, Argobots uses this function only for a private pool.

There is a large room for improvement (though it may require changes in other parts of code).

6. ULT and tasklet are managed separately (`ABT_unit_get_type_fn()`, `ABT_unit_get_thread_fn()`, ...), which is inefficient. Internally both are `ABTI_unit`, so potentially they can be managed in the same way.
7. This PR is a promising direction to enhance the flexibility of pool implementations.
   - https://lists.argobots.org/pipermail/discuss/2020-July/000080.html

These require fundamental changes in the pool interface, though.  Perhaps we need to create another interface (e.g., `ABT_pool2`).
