### ISSUE TITLE
threads with user-provided stacks: Need stack free hook

### ISSUE THREAD

**Issue by u-u-h** [pmodels/argobots#16]
When a user-provided stack is passed as stack attribute in `ABT_thread_create() `there is no easy way to reclaim that memory (say, to re-use it for another ABT_thread). 
Unnamed threads clean up their stack at the end of `ABTI_thread_free()` using `ABTI_mem_free_thread()`, but `ABTI_EXT_STACK` cases take a fast path there.

It seems awkward to require the user to move to named threads, keep all thread handles, and poll them for their 'finished' status, or start extra threads just to do the joins only for the stack handling.

I'd think the simplest solution would be to add a stack cleanup function parameter in the thread attribute data, which would be called `ABTI_thread_free()`, or in `ABTI_mem_free_thread()`. A closure parameter would of course be appreciated for that function.

--uuh

**Comment by halimamer** [comment]
@u-u-h , the "bring-your-stack" feature was originally added to ease portability of Pthread codes to Argobots. In other words, it is not a "necessary" feature. Although giving users fine-grained control over the stack size is useful to run functions with large stack footprint, letting them manage everything about the stack seems less useful. We recommend users to let  Argobots manage stack memory because in most cases it can do a better job at reusing the reclaimed memory, reducing the allocation cost, and so on (c.f. http://www.mcs.anl.gov/papers/P5515-0116.pdf for some details on how we manage memory).
We plan to deprecate this user-provided stack feature. We advise you to not do so and instead let Argobots manage the stack address, which will allow you to use unnamed threads without worrying about garbage collection.

If you think you can do a better job than Argobots at managing stack memory, then please let us know how you do that so that we consider it for a future improvement.

**Comment by u-u-h** [comment]
This is is a very unfortunate plan, and I hope you can be convinced that the flexibility is worth preserving.

In general I do like the stack memory management implementation you have, it seems like a very reasonable general purpose choice. Nevertheless, in the code we are working on we see significantly better performance with user-provided stacks (large stacks, and a clear strategy to reuse them). 

In rare cases we would like to schedule threads that can share the same stack allocation (because we know they will run sequentially), to save allocations.

Furthermore, diagnosing stack overflow issues is almost impossible without user-provided stacks, as overflows often silently corrupt the next_stack bookkeeping structures of argobots. User-allocated stack regions will show up in memory tracking tools, or can be terminated by guard pages explicitly.

--uuh

**Comment by halimamer** [comment]
Sorry for the long delay on responding. There are two issues that you are mentioning; one regarding performance and the second is related debugging.

First, I would be surprised if our stack memory reuse is performing significantly worse than the reuse strategy you implemented. We might be doing something wrong here, thus, I would really like to look into a sample code that shows this issue for investigation. By understanding better the poor reuse problem, we will fix it accordingly. If we cannot transparently handle your case, then leaving the user-managed stack would then make sens. Could you provide us with a sample code that we can work with?

From a debugging perspective, I don't understand how a user-provided stacks would be better for debugging overflows. Could you give an example code as well? Thanks.

**Comment by halimamer** [comment]
@u-u-h , FWIW, Argobots has a `revive` feature that is useful for reusing a thread's data structure. The flow is as follows: `create`, [`join`, [`revive`]]*, `free`. In other words, you can join and revive the same thread multiple times before reclaiming its memory. When reviving, you can use a different function pointer than at creation time

**Comment by shintaro-iwasaki** [comment]
Sorry for the very late reply. I realized that we can do the same thing by using `ABT_key_create`:

```c
void stack_free_callback(void *stack) {
    munmap(stack, PREDEFINED_MMAP_STACK_SIZE);
}
ABT_key g_stack_key;
/* ABT_key_create(stack_free_callback, &g_stack_key); */

void thread() {
    /* The created thread needs to know "stack".
     * The ULT-local value will be freed by stack_free_callback() on ABT_thread_free(). */
    ABT_key_set(g_stack_key, stack);
}

void thread_create() {
    stack = mmap(...);
    ABT_thread_create(...);
    ABT_thread_free(...);
}
```

If we do not need a very special method for this memory hook, this is a practical and general solution to call a hook. Please reopen this issue if you need a more advanced mechanism.
