### ISSUE TITLE
mutexes busy spin by default even when using _WAIT scheduler and pool variants

### ISSUE THREAD

**Issue by carns** [pmodels/argobots#361]
See discussion on mailing list at https://lists.argobots.org/pipermail/discuss/2021-July/000157.html.

Confirmed with a Margo unit test in a development branch at https://github.com/mochi-hpc/mochi-margo/blob/carns/dev-scheduling-test/tests/unit-tests/margo-scheduling.c.  The following example shows swapping out two argobots libraries with the only change being whether the simple mutex implementation is enabled (default) or disabled.  This configuration change is enacted with a modified spack package that includes a "simple-mutex" variant. The test program deliberately sets up a scenario in which a ULT will attempt to lock a mutex that is held by another ULT for roughly 5 seconds.

The default behavior consumes user CPU time for the duration of the test case.  The simple mutex consumes negligible user CPU time.

```
> spack load -r argobots+simple-mutex
> tests/unit-tests/margo-scheduling
Running test suite with seed 0xdbb2a8d1...
/margo/abt_mutex_cpu                 user CPU time used: 5.086535
[ OK    ] [ 5.20039447 / 5.08659853 CPU ]
1 of 1 (100%) tests successful, 0 (0%) test skipped.
> spack  unload argobots
> spack load -r argobots~simple-mutex
> tests/unit-tests/margo-scheduling
Running test suite with seed 0x45d7f56c...
/margo/abt_mutex_cpu                 user CPU time used: 0.001290
[ OK    ] [ 5.20056152 / 0.00491515 CPU ]
1 of 1 (100%) tests successful, 0 (0%) test skipped.
```

This is problematic for I/O oriented use cases (Margo and more generally Mochi) in which ULTs are really just blocking on peripheral resource availability.  Sometimes our execution streams are over-provisioned according to the characteristics of the platform, and we would prefer to use CPU time for other purposes (or make it available for co-located processes). I don't have a specific application example for  which this is a problem, but we suspect that it has confused some debugging efforts in the past by causing some nominally "just waiting for access to an I/O device" execution streams to consume CPU.

I don't know what the implications are of the mutex implementation (beyond the CPU usage).  For our use case in isolation it would be better (in order of preference) to a) toggle the default behavior or b) have the capability to toggle it at runtime (so that we can gain this capability without altering the argobots build) or c) if it is a build-time option, make it accessible via upstream spack variant.

There was a point in the past in which Argobots mutexes did not behave well when the number of execution streams exceeded the number of CPU cores on the node, but I don't know if the mutex type has any bearing on that historical issue.

**Comment by shintaro-iwasaki** [comment]
@carns. Thank you very much for pointing out this issue.

> The default behavior consumes user CPU time for the duration of the test case. The simple mutex consumes negligible user CPU time.

The current option is complicated, but I assume that 
- `The default behavior`: implicitly setting `--enable-simple-mutex` (default Argobots choice).
- `The simple mutex`: explicitly disabling the simple mutex setting by `--disable-simple-mutex`.

> There was a point in the past in which Argobots mutexes did not behave well when the number of execution streams exceeded the number of CPU cores on the node, but I don't know if the mutex type has any bearing on that historical issue.

This issue has been fixed.  At least, Argobots 1.1 does not have this issue.  Argobots does not rely on `ABT_MAX_NUM_XSTREAMS`.

---

The current mutex behavior is different from other synchronization objects, which suspend other waiters unlike the default "simple" mutex.  So the current default mutex behavior should be confusing as @carns pointed out.

I prefer (a) toggle the default behavior because this non-simple behavior is what the user should expect.  I will keep the `--enable-simple-mutex` option for the backward compatibility, but we might want to remove this in the future.

If no one wants to keep this "simple mutex" as the behavior configuration (and anyway `--enable-simple-mutex` will be supported for a while), I will create a PR and toggle this configuration option. I planned to make a PR this weekend (to make sure that everyone has time to read this issue).

**Comment by carns** [comment]
Thanks @shintaro-iwasaki , that sounds great to me.

**Comment by carns** [comment]
Thank you @shintaro-iwasaki !

**Comment by carns** [comment]
Actually one more question here.  Is there any way at compile or run time to detect which mutex mechanism a given Argobots build is using?

**Comment by shintaro-iwasaki** [comment]
@carns Currently Argobots does not expose this information at neither compile nor run-time since this is regarded as an internal implementation difference (i.e., no functionality difference). Currently, the only way is  really running mutex code at run-time and checking whether a waiting ULT yields (=simple) or suspends (=likely to be not simple).

This setting can significantly affect the behavior (including performance) of the user program, so I am happy to expose this information via `ABT_info_query_config()`. Since the current Argobots (i.e., Argobots >= v1.2) disables simple mutex by default and I believe no one will turn it on, however, I am not sure if this change is useful.

**Comment by carns** [comment]
Ok.  My use case is that I have a unit test in Margo to check if mutexes are busy spinning or not (by comparing user cpu time and wall time).  Right now I just have it always report success and log the result, since I don't know whether it will be executed against an Argobots build that is configured one way or the other and I don't want our unit tests to fail on old Argobots builds.

If there were a query_config option I could check for I would use it (if the config param is present, is it set to the expected value, and then does the mutex actually behave as expected), but it's not that important.
