### ISSUE TITLE
Suggestion: add an ABT_EVENTUAL_INITIALIZER and ABT_eventual_memory

### ISSUE THREAD

**Issue by mdorier** [pmodels/argobots#362]
If it's possible, adding the same mechanism as for mutex and condition variables to initialize an eventual in static memory would be very useful.

**Comment by shintaro-iwasaki** [comment]
Thank you for your suggestion. If it is useful, yes we are happy to implement it. The mechanism will be the same as `ABT_mutex` and `ABT_cond` (so I will create `ABT_eventual_memory`, `ABT_EVENTUAL_INITIALIZER`, and `ABT_EVENTUAL_MEMORY_GET_HANDLE`). I will create a PR within a week or so.

Just in case: is this following behavior okay for you?
```c
int ABT_eventual_create(int nbytes, ABT_eventual *neweventual)
```
`nbytes` cannot be passed to the static initializer (since it internally needs `nbytes`-byte memory), so statically initialized `ABT_eventual` uses `nbytes=0`.

**Comment by mdorier** [comment]
Yes, in the context of a static eventuals we can work around the `nbytes` by defining a structure that packs an `ABT_eventual_memory` with whatever data needs to be set.
