### ISSUE TITLE
"automatic" argument ignored in ABT_pool

### ISSUE THREAD

**Issue by dorier** [pmodels/argobots#58]
When creating a pool with `ABT_pool_create_basic`, no matter whether the "automatic" argument is set to `ABT_TRUE`, or `ABT_FALSE`, the pool is going to be destroyed when no scheduler is using it anymore. Attempting to call `ABT_pool_free` leads to a double-free corruption.

Here is an example program:

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "abt.h"

#define NUM_XSTREAMS    4
#define NUM_THREADS     (NUM_XSTREAMS * 2)

void thread_hello(void *arg)
{
		sleep(1);
		int rank, tid = (int)(size_t)arg;
		ABT_xstream_self_rank(&rank);
		printf("[U%d:E%d] Hello, world!\n", tid, rank);
}

int main(int argc, char *argv[])
{
		ABT_xstream xstreams[NUM_XSTREAMS];
		ABT_sched   scheds[NUM_XSTREAMS];
		ABT_pool    shared_pool;
		ABT_thread  threads[NUM_THREADS];
		int i;

		ABT_init(argc, argv);

		/* Create a shared pool */
		ABT_pool_create_basic(ABT_POOL_FIFO, ABT_POOL_ACCESS_MPMC,
						ABT_FALSE, &shared_pool);

		/* Create schedulers */
		for (i = 0; i < NUM_XSTREAMS; i++) {
				ABT_sched_create_basic(ABT_SCHED_DEFAULT, 1, &shared_pool,
								ABT_SCHED_CONFIG_NULL, &scheds[i]);
		}

		/* Create ESs */
		ABT_xstream_self(&xstreams[0]);
		ABT_xstream_set_main_sched(xstreams[0], scheds[0]);
		for (i = 1; i < NUM_XSTREAMS; i++) {
				ABT_xstream_create(scheds[i], &xstreams[i]);
		}

		/* Create ULTs */
		for (i = 0; i < NUM_THREADS; i++) {
				size_t tid = (size_t)i;
				ABT_thread_create(shared_pool, thread_hello, (void *)tid,
								ABT_THREAD_ATTR_NULL, &threads[i]);
		}

		/* Join & Free */
		for (i = 0; i < NUM_THREADS; i++) {
				ABT_thread_join(threads[i]);
				ABT_thread_free(&threads[i]);
		}

		for (i = 1; i < NUM_XSTREAMS; i++) {
				ABT_xstream_join(xstreams[i]);
				ABT_xstream_free(&xstreams[i]);
		}

		ABT_pool_free(&shared_pool);
        
		ABT_finalize();

		return 0;
}
```

**Comment by dorier** [comment]
I'll add some more fun to the problem: from my experience, the `automatic=ABT_FALSE` seems to be ignored for pools created with `ABT_pool_create_basic`. Pools created with `ABT_pool_create` (i.e. custom pools) do need to be freed by the user, using `ABT_pool_free`. They are not freed automatically.

So basically right now if part of my code is being given a pool, with the responsibility of managing it (including destroying it if needed), there is no way of knowing if I should call `ABT_pool_free` or not, because this depends on whether the pool was created as a basic pool, or as a custom pool.

**Comment by shintaro-iwasaki** [comment]
This complicated and confusing behavior is not a bug.
You pointed out two problems:

1. pool is freed no matter `automatic` is set to `ABT_TRUE` or `ABT_FALSE`.

This SEGV happens because `shared_pool` is freed though the main scheduler (`scheds[0]`) is still pointing to that pool. In `ABT_finalize()`, the main scheduler is released. In this process, all pools including `shared_pool` managed by the main scheduler are accessed to check if it should be automatically freed or not (and freed in the given case.) Of course, that pool has been already freed, so such an access is illegal.

I think it is natural to forbid freeing pools that are still used by schedulers. However, because there is no way to free what the main scheduler manages (including `ABT_sched` and `ABT_pool`), they must be freed by the runtime. Currently, Argobots does not allow users to use any Argobots functions after calling `ABT_finalize()`. This issue can be easily addressed by adding a reference counter (see https://github.com/shintaro-iwasaki/argobots/tree/FixPoolAutomatic), but this solution is beyond the specification because it allows using ABT_pool_free` while schedulers are still using that pool.

2. `ABT_pool_create` and `automatic`

There is no interface to set `automatic` of a pool that is created by `ABT_pool_create`. `automatic` is always `ABT_FALSE`. As you mentioned, it is inconvenient. I think future pool creation APIs should take `automatic`.

**Comment by mdorier** [comment]
I'm coming back to this old issue. I have modified my code in the first post to better understand what is happening. This is the new code:

```c
#include <abt.h>
#include <stddef.h>
#include <stdio.h>

#define NUM_XSTREAMS 4
#define NUM_THREADS 8

void thread_hello(void* arg) {
    printf("Hello World\n");
}

int main(int argc, char *argv[])
{
    ABT_xstream xstreams[NUM_XSTREAMS];
    ABT_sched   scheds[NUM_XSTREAMS];
    ABT_pool    shared_pool;
    ABT_thread  threads[NUM_THREADS];
    int i;

    ABT_init(argc, argv);

    /* Create a shared pool */
    ABT_pool_create_basic(ABT_POOL_FIFO, ABT_POOL_ACCESS_MPMC,
            ABT_FALSE, &shared_pool);

    /* Create schedulers */
    for (i = 0; i < NUM_XSTREAMS; i++) {
        ABT_sched_create_basic(ABT_SCHED_DEFAULT, 1, &shared_pool,
                ABT_SCHED_CONFIG_NULL, &scheds[i]);
    }

    /* Create ESs */
    ABT_xstream_self(&xstreams[0]);
    ABT_xstream_set_main_sched(xstreams[0], scheds[0]);
    for (i = 1; i < NUM_XSTREAMS; i++) {
        ABT_xstream_create(scheds[i], &xstreams[i]);
    }

    /* Create ULTs */
    for (i = 0; i < NUM_THREADS; i++) {
        size_t tid = (size_t)i;
        ABT_thread_create(shared_pool, thread_hello, (void *)tid,
                ABT_THREAD_ATTR_NULL, &threads[i]);
    }

    /* Join & Free */
    for (i = 0; i < NUM_THREADS; i++) {
        ABT_thread_join(threads[i]);
        ABT_thread_free(&threads[i]);
    }

    for (i = 1; i < NUM_XSTREAMS; i++) {
        ABT_xstream_join(xstreams[i]);
        ABT_xstream_free(&xstreams[i]);
    }

    // create a fake pool and scheduler to attach to the xstream so that the
    // real scheduler and pool can be freed manually
    ABT_pool fake_pool;
    ABT_sched fake_sched;
    ABT_pool_create_basic(ABT_POOL_FIFO, ABT_POOL_ACCESS_MPMC,
                          ABT_TRUE, &fake_pool);
    ABT_sched_create_basic(ABT_SCHED_DEFAULT, 1, &fake_pool,
                           ABT_SCHED_CONFIG_NULL, &fake_sched);
    ABT_xstream_set_main_sched(xstreams[0], fake_sched);

    ABT_pool_free(&shared_pool);
    ABT_finalize();

    return 0;
}
```

What I'm doing here is this:

- Create a shared pool
- Create 4 schedulers attached to the shared pool
- Create 3 ES (so we have 4 including primary)
- Set the scheduler of each ES to the schedulers created before
- Run 8 ULTs that are created on the shared pool

My end goal is to be able to manually free the shared pool. With Argobots 1.0.0, my original code doesn't segfault anymore, but it blocks on the `ABT_pool_free`. I suppose this is because ES 0 is still alive, with a scheduler that is using the pool.

With the new code, to make sure the remaining scheduler that uses the shared pool is destroyed before I call `ABT_pool_free`, I create a "fake pool" (this time with automatic = true) and a "fake scheduler" associated to it, then I set the scheduler of the primary ES to this new scheduler. Since schedulers are automatically freed when they are not associated with an ES anymore, this effectively frees the original scheduler I had created, and makes it possible to manually free the shared pool.

Most importantly, it seems that `ABT_pool_free` now blocks if the pool is still referenced by a scheduler. Can I always count on that to be true?
If I use `ABT_sched_config` to set automatic to false for a scheduler, can I also count on the `ABT_sched_free` blocking (not leading to a segfault) if I try to free a scheduler that is still used by an ES?

**Comment by shintaro-iwasaki** [comment]
> Most importantly, it seems that ABT_pool_free now blocks if the pool is still referenced by a scheduler. Can I always count on that to be true?

Briefly speaking, this is not true. Users need to be responsible for the timing of free.

In my understanding, there is no protection mechanism employed in `ABT_pool_free()` and `ABT_sched_free()` regardless of the value of `automatic`, so if one uses `ABTI_XXX_free()` while other schedulers are using / will use them, it causes SEGV (or any weird behavior). `ABT_xstream_set_main_sched()` performs "incomplete" synchronization when it frees an original scheduler, so it may look like a "blocking" behavior.

(This blocking mechanism is incomplete because it still relies on users to guarantee freed schedulers and pools are not referenced in the future. For example, `ABT_xstream_set_main_sched()` might prematurely frees a pool (or do not do "blocking") in the following case: the pool reference counter becomes "zero" when the last ULT is popped from that pool and thus the pool is freed, but the pool is accessed after that since `ABT_thread_yield()` is performed on the last ULT.)

It is usually a good idea if one just ignores a certain pool if it becomes unnecessary (e.g., by adding a branch in the pool selection logic of the scheduler) but still relies on `automatic=true` for actual freeing, unless one really need to dynamically create and destroy pools and schedulers during execution.

**Comment by mdorier** [comment]
I see, thanks. So the blocking behavior I was seeing was by chance, sort of; in other situations it could very well segfault.

**Comment by shintaro-iwasaki** [comment]
#282 clarifies the default behavior of automatic resource release of `ABT_pool`, although the current behavior is fundamentally confusing. I will close this issue. If you find any other issues, please let us know.
