### ISSUE TITLE
No way of preventing Argobots from freeing a scheduler

### ISSUE THREAD

**Issue by dorier** [pmodels/argobots#59]
Argobots schedulers are freed automatically when no ES is using them anymore, there is no way to do things like the following without having to re-create a scheduler:

- Create a pool P
- Create a scheduler S (make it use pool S)
- Create an ES A (make it use scheduler S)
- Joins ES A
- Free ES A
- Create ES B (make it use scheduler S) <-- here the scheduler has been freed

The solution seems to be in defining a `ABT_sched_config` config and setting `ABT_sched_config_automatic` to `ABT_TRUE`, however `ABT_sched_config_automatic` doesn't seem to be implemented (nor is `ABT_sched_basic_freq`, by the way).

**Comment by dorier** [comment]
Similar to the pool's automatic freeing problem (see https://github.com/pmodels/argobots/issues/58): custom schedulers *do not* get freed automatically, contrary to basic schedulers, which forces any user code that is being passed an ABT_sched to be also passed whether this is a custom scheduler or not. (rather inconvenient)

**Comment by shintaro-iwasaki** [comment]
Thank you for reporting the issue. #62 should alleviate the issue.

I would like to note two things:

1. Do not free the main scheduler of the primary xstream manually.
`ABT_finalize()` must free "the main scheduler of the primary xstream" because the primary xstream is still using it before `ABT_finalize()` and there is no way to free it after `ABT_finalize()` (Argobots does not allow users to call Argobots functions after finalization.) And, `automatic` of such a scheduler is automatically updated to `ABT_TRUE` in `ABTI_xstream_set_main_sched` (please see `ABTI_xstream_set_main_sched` in `stream.c` for details.)

2. A default `automatic` value varies. Set `ABT_sched_config_automatic` manually for better management.
In `ABT_sched_create`, `ABT_FALSE` is the default `automatic`, while `ABT_FALSE` in `ABT_sched_create_basic`.

I don't think their design is good, though. Future APIs will address them, I hope.

**Comment by shintaro-iwasaki** [comment]
#281 clarifies this confusing behavior. ce9d0dd45b283fffabc53f04f1331b02569838c9 in #281 also fixes a bug regarding this automatic behavior when you use `ABT_sched_create()` (`ABT_sched_create_basic()` did not have this issue). If you find any issues, please let us know.
