### ISSUE TITLE
ARM build fails due to ABT_CONFIG_USE_FCONTEXT being unset

### ISSUE THREAD

**Issue by dorier** [pmodels/argobots#81]
Same issue as https://github.com/pmodels/argobots/issues/18 and https://github.com/pmodels/argobots/issues/11 but for ARM platforms. The previous issues have been closed a while ago. Any plan to add full support for ucontext when fcontext isn't available?

**Comment by shintaro-iwasaki** [comment]
Thank you for your report. Since it causes several compilation issues, we will support the ucontext version soon.

Apart from the ucontext support that should be done anyway in the near future, ucontext is slow and thus used as a backup method. fcontext should support major architectures such as x86/64, ARM, and Power. Previously the architecture detection failed (#18). I assume that 64-bit ARM should return `aarch64`, unless your environment uses special/new architecture and/or ABI (i.e., calling convention).

Can you run `lscpu` and tell me "Architecure" (which should be equal to `$host_cpu` in the `configure` scripts)?

**Comment by mdorier** [comment]
There seems to be some support for fcontext in ARM now in Boost:
https://github.com/boostorg/context/tree/develop/src/asm
Maybe time to integrate it in Argobots?

**Comment by mdorier** [comment]
Note that my issue earlier was with ARM 32bits (Rasbian on Raspberry Pi), not aarch64.

**Comment by shintaro-iwasaki** [comment]
Oh, I see. Now we don't have ARM 32 bits supports.
We cannot just simply copy the Boost codes to Argobots, we need to customize them somehow (e.g., making `take_fcontext`.) Unfortunately, ARM 32 bits is not a major architecture in HPC, so the support is of low priority.

If you need it beyond your pure curiosity, we/I might work on it; if this is the case, please let me know.

JFYI, #100 will revive the ucontext support, so with this, I hope you can run Argobots on Raspberry Pi

**Comment by mdorier** [comment]
It's more of a curiosity/convenience thing; I'm sometimes using a couple of Raspberry Pi to test out distributed code, and I thought since Boost now supports ARM32 it might be easier than bringing back to ucontext. But if the ucontext works, then great!

**Comment by shintaro-iwasaki** [comment]
ucontext is supported by #100. I haven't tested, but I hope Argobots now works on 32-bit ARM.

**Comment by shintaro-iwasaki** [comment]
Since ucontext is now supported, Argobots should work on 32-bit ARM.
The problem of ucontext is performance; it is slower than fcontext. However, fcontext support requires assembly programming and *testing*; unfortunately, we don't have a 32-bit ARM machine.

I don't think there are limited HPC use cases of Argobots on 32-bit ARM machines; it should be mainly for testing. If really needed (e.g.,, for low-power Raspberry Pi clusters), please let us know.
